[project]
name = "shooter-game"
description = "Shooter Game Clarity smart contract"
authors = ["W3P Team"]
license = "MIT"

[project.requirements]
clarinet = ">=1.0.0"

[contracts.shooter-game]
path = "contracts/shooter-game.clar"

[networks.testnet]
stacks_node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
stacks_node_p2p_address = "https://stacks-node-api.testnet.stacks.co"
stacks_network_id = "testnet"
deployment_fee_tx_sender = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"

[networks.mainnet]
stacks_node_rpc_address = "https://stacks-node-api.mainnet.stacks.co"
stacks_node_p2p_address = "https://stacks-node-api.mainnet.stacks.co"
stacks_network_id = "mainnet"
deployment_fee_tx_sender = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9"

[devnet]
disable_telemetry = false
